CREATE TABLE sec_company (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
  PRIMARY KEY (id)
);

CREATE TABLE sec_branch (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(150) DEFAULT NULL UNIQUE,
  name VARCHAR(50) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL ,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  company_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_company (company_id) USING BTREE,
  CONSTRAINT cs_branch_company FOREIGN KEY (company_id) REFERENCES sec_company (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE sec_user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT ,
  code VARCHAR (50) NOT NULL UNIQUE COMMENT 'Code As User Name',
  name VARCHAR(150) DEFAULT NULL COMMENT 'First Name of Profile',
  remarks VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on DATETIME DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  password VARCHAR (255),
  enabled BOOLEAN DEFAULT TRUE ,
  expired_date DATETIME DEFAULT NULL ,
  account_non_locked BOOLEAN DEFAULT TRUE,
  login_status BOOLEAN DEFAULT FALSE ,
  last_login DATETIME DEFAULT NULL ,
  credentials_expired_date DATETIME DEFAULT NULL ,
  branch_id BIGINT(20),
  PRIMARY KEY (id),
  KEY fk_branch (branch_id),
  CONSTRAINT cs_user_branch FOREIGN KEY(branch_id) REFERENCES sec_branch(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE sec_user_verification (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  token varchar(255) DEFAULT NULL UNIQUE ,
  expiry_date datetime DEFAULT NULL COMMENT 'Expiry time in minutes',
  user_id bigint(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_user (user_id) USING BTREE,
  CONSTRAINT cs_verification_user FOREIGN KEY(user_id) REFERENCES sec_user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE mst_contact (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on DATETIME DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  first_name VARCHAR(50) DEFAULT NULL,
  last_name VARCHAR(50) DEFAULT NULL,
  personal_number VARCHAR(50) DEFAULT NULL,
  phone_number_1 VARCHAR(50) DEFAULT NULL,
  phone_number_2 VARCHAR(50) DEFAULT NULL,
  fax_number VARCHAR(50) DEFAULT NULL,
  postal_code VARCHAR(10) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE mst_country (
  id BIGINT(50) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on DATETIME DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE mst_province (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  country_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_country (country_id),
  CONSTRAINT cs_province_country FOREIGN KEY(country_id) REFERENCES mst_country(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE mst_city (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  province_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_province (province_id) USING BTREE,
  CONSTRAINT cs_city_province FOREIGN KEY (province_id) REFERENCES mst_province (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE mst_district (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  city_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_city (city_id) USING BTREE,
  CONSTRAINT cs_district_city FOREIGN KEY (city_id) REFERENCES mst_city (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE mst_village (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL ,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  district_id BIGINT(20) DEFAULT NULL,
  number_of_family_leader INTEGER DEFAULT NULL ,
  latitude VARCHAR(100) DEFAULT NULL,
  longitude VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_district_id (district_id) USING BTREE,
  CONSTRAINT cs_village_district FOREIGN KEY (district_id) REFERENCES mst_district (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE mst_address (
  id BIGINT(50) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  detail_address mediumtext,
  province_id BIGINT(20) DEFAULT NULL,
  city_id BIGINT(20) DEFAULT NULL,
  district_id BIGINT(20) DEFAULT NULL,
  country_id BIGINT(20) DEFAULT NULL,
  village_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_country_id (country_id) USING BTREE,
  KEY fk_province_id (province_id) USING BTREE,
  KEY fk_city_id (city_id) USING BTREE,
  KEY fk_district_id (district_id) USING BTREE,
  KEY fk_village_id (village_id) USING BTREE,
  CONSTRAINT cs_address_province FOREIGN KEY (province_id) REFERENCES mst_province (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_address_city FOREIGN KEY (city_id) REFERENCES mst_city (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_address_district FOREIGN KEY (district_id) REFERENCES mst_district (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_address_country FOREIGN KEY (country_id) REFERENCES mst_country (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_address_village FOREIGN KEY (village_id) REFERENCES mst_village (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE mst_locale (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE mst_identity_type (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);


CREATE TABLE sec_user_profile (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL,
  gender TINYINT(1) DEFAULT NULL COMMENT '1=man\r\n0=woman',
  birth_date date DEFAULT NULL,
  profile_photo VARCHAR(255) DEFAULT NULL,
  birth_place VARCHAR(150) DEFAULT NULL,
  id_number VARCHAR(100) DEFAULT NULL,
  address_id BIGINT(20) DEFAULT NULL,
  contact_id BIGINT(20) DEFAULT NULL,
  user_id BIGINT(20) DEFAULT NULL,
  locale_id BIGINT(20) DEFAULT NULL ,
  id_type_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_user (user_id) USING BTREE,
  KEY fk_address_user (address_id) USING BTREE,
  KEY fk_contact_user (contact_id) USING BTREE,
  KEY fk_locale_id (locale_id) USING BTREE,
  KEY fk_sec_user_profile_id_type (id_type_id),
  CONSTRAINT cs_user_profile FOREIGN KEY(user_id) REFERENCES sec_user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_profile_id_type FOREIGN KEY (id_type_id) REFERENCES mst_identity_type (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT cs_profile_address FOREIGN KEY (address_id) REFERENCES mst_address (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_profile_contact FOREIGN KEY (contact_id) REFERENCES mst_contact (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_profile_locale FOREIGN KEY (locale_id) REFERENCES mst_locale (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE sec_role (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(50) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL ,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE link_user_role (
  user_id BIGINT(20),
  role_id BIGINT(20),
  PRIMARY KEY (user_id, role_id),
  KEY fk_link_user_user_idx (role_id),
  CONSTRAINT cs_link_user_user FOREIGN KEY (user_id) REFERENCES sec_user (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_link_user_role FOREIGN KEY (role_id) REFERENCES sec_role (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE sec_function (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  url VARCHAR(150) DEFAULT NULL,
  style VARCHAR(150) DEFAULT NULL,
  function_order INTEGER DEFAULT NULL ,
  parent_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_parent_id (parent_id) USING BTREE,
  CONSTRAINT cs_function_parent FOREIGN KEY (parent_id) REFERENCES sec_function (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE sec_function_assignment (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) DEFAULT NULL UNIQUE,
  name VARCHAR(150) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_on TIMESTAMP NULL DEFAULT NULL,
  modified_by VARCHAR(50) DEFAULT NULL,
  modified_on TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  role_id BIGINT(20) DEFAULT NULL ,
  function_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY fk_function (function_id) USING BTREE,
  KEY fk_role (role_id) USING BTREE,
  CONSTRAINT cs_function_assignment_function FOREIGN KEY (function_id) REFERENCES sec_function (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cs_function_assignment_role FOREIGN KEY (role_id) REFERENCES sec_role (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE trx_import_data (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  upload_start_date DATETIME NULL DEFAULT NULL ,
  upload_end_date DATETIME NULL DEFAULT NULL ,
  upload_status TINYINT(1) DEFAULT NULL ,
  file_path VARCHAR(255) DEFAULT NULL ,
  file_size BIGINT(20) DEFAULT NULL ,
  file_type VARCHAR (150) DEFAULT NULL ,
  import_start_date DATETIME NULL DEFAULT NULL ,
  import_end_date DATETIME NULL DEFAULT NULL ,
  import_status TINYINT(1) DEFAULT NULL ,
  PRIMARY KEY (id)
);