#============================================================================
# DATABASE
#============================================================================
db:
  name : lsi_security
  host : localhost
  port : 3306
  username : root
  password : P@ssw0rd
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/LSI/SEC/lsi-security.log