#============================================================================
# DATABASE
#============================================================================
db:
  name : lsi_security
  host : 103.77.78.248
  port : 3306
  username : trplsi
  password : trplsi0123()**!
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /log/webservice/LSI/SECURITY/lsi-security.log