#============================================================================
# DB
#============================================================================
db:
  name : wissensalt-log
  host : localhost
  port : 27017

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/plustix-api-logger/log/plustix-api-logger.log

#============================================================================
# RABBIT MQ
#============================================================================
rabbitmq:
  host : 127.0.0.1
  port : 5672
  username : guest
  password : guest