#============================================================================
# DB
#============================================================================
db:
  name : lsi-log
  host : 103.77.78.248
  port : 27017
  database : lsi-log
  authentication-database : admin
  username : mongo
  password : trplsimng0123#!
  repositories : true


#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/PLUSTIX/API-LOGGER/plustix-api-logger.log

#============================================================================
# RABBIT MQ
#============================================================================
rabbitmq:
  host : 127.0.0.1
  port : 5672
  username : guest
  password : guest