#============================================================================
# DATABASE
#============================================================================
db:
  name : lsi_core
  host : 103.77.78.248
  port : 3306
  username : trplsi
  password : trplsi0123()**!
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/LSI/CORE/lsi-thirdparty.log
  base:
    path : http://103.77.78.248:9001/lsi-api-logger


#============================================================================
# OAUTH 2.0 | SSO
#============================================================================
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: app_client_id
      clientSecret: my-secret-app
      accessTokenUri: http://103.77.78.248:10002/lsi-security-oauth2/oauth/token
      userAuthorizationUri: http://103.77.78.248:10002/lsi-security-oauth2/oauth/authorize
    resource:
      userInfoUri: http://103.77.78.248:10002/lsi-security-oauth2/principal/me

feign:
  acl :
    api :
      base-path : http://103.77.78.248:9002/lsi-acl