#============================================================================
# SERVER
#============================================================================
server:
  port: 9002
  context-path: /lsi-acl
  connection-timeout : 30000 #in milisecond

#============================================================================
# SPRING
#============================================================================
spring:
  servlet :
    multipart :
      location : /home/fauzi/tmp_upload
      enabled : true
      file-size-threshold : 2KB
      max-file-size : 250MB
      max-request-size : 1000MB
  application:
    name: lsi-acl
  profiles:
    active : prod
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://${db.host}:${db.port}/${db.name}?autoReconnect=${db.auto-reconnect}&useSSL=${db.ssl}
    username : ${db.username}
    password : ${db.password}
  jpa:
    show-sql: false
    properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
            ddl-auto : validate     # Hibernate ddl auto (create, create-drop, validate, update)

#============================================================================
# DATABASE
#============================================================================
db:
  name : lsi_security
  host : localhost
  port : 3306
  username : root
  password : P@ssw0rd
  auto-reconnect : true
  ssl : false

#============================================================================
# ACTUATOR
#============================================================================
management:
  context-path : /actuator
  security:
    enabled: false
    roles: ROLE_ACTUATOR

#============================================================================
# LOGGER
#============================================================================
logging:
  config: classpath:logback-spring.xml
  file : ${log.file.path}
  level:
    com.wissensalt.scaffolding.client: DEBUG
  api :
    base-path : ${log.base.path}

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/LSI/ACL/lsi-acl.log
  base:
    path : http://localhost:9001/lsi-api-logger

#============================================================================
# JWT
#============================================================================
jwt:
  secret: my-secret-app
  header: x-auth-token
# expiration in seconds
  expiration: 1800
  refresh-multiplier: 3
  cookie : JWT-AUTH
  auth:
    url : http://localhost:10002/lsi-security-oauth2/security/auth/login

#============================================================================
# OAUTH 2.0 | SSO
#============================================================================
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: app_client_id
      clientSecret: my-secret-app
      accessTokenUri: http://localhost:10002/lsi-security-oauth2/oauth/token
      userAuthorizationUri: http://localhost:10002/lsi-security-oauth2/oauth/authorize
    resource:
      userInfoUri: http://localhost:10002/lsi-security-oauth2/principal/me

sso-jwt : false

#============================================================================
# SWAGGER
#============================================================================
swagger :
  vendor :
    name : Lsi
    value : 1.0.0
  metadata :
    title : LSI - API ACL
    description : ACL Services for Lsi
    version : 1.0.0
    tos : This Documentation is Only Available on Development Phase
    license : Apache License Version 2.0
    license-url : https://www.apache.org/licenses/LICENSE-2.0
    contact :
      name : Achmad Fauzi
      url : https://tripoin.co.id
      email : fauzi.knightmaster.achmad@gmail.com

#============================================================================
# DISCOVERY CLIENT
#============================================================================
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#  instance :
#    home-page-url : http://localhost:9002/
#    status-page-url-path : http://localhost:9002/actuator/info
#    health-check-url-path : http://localhost:9002/actuator/health

#============================================================================
# DISCOVERY CLIENT
#============================================================================
#info:
#  app:
#    name: ACL Application
#    description: API for Access Control List (Authorization) within Plustix System
#    version: 1.0.0

#============================================================================
# FILE
#============================================================================
file :
  upload :
    dir : /home/fauzi/upload