#============================================================================
# DATABASE
#============================================================================
db:
  name : plustix_security
  host : localhost
  port : 3306
  username : root
#  password : C14sDevS1gm42016r00t.
  password : P@ssw0rd
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/plustix/plustix-acl/log/plustix-acl.log