#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/plustix/plustix-discovery-server/log/plustix-discovery.log