#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/plustix/plustix-api-gateway/log/plustix-gateway.log