#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/PLUSTIX/GATEWAY/plustix-gateway.log