#============================================================================
# SERVER
#============================================================================
server:
  tomcat:
    max-threads : 4000
  port: 8081
  context-path: /lsi-core
  compression :
    enabled : true
    mime-types : text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  connection-timeout : 30000 #in milisecond
  #session:
    #timeout: 10         # session timeout in second
    #cookie:
      #max-age: 10     # Maximum age of the session cookie in seconds. also add if server.session.timeout not working

#============================================================================
# SPRING
#============================================================================
spring:
#  mvc :
#    async:
#      request-timeout : 30000
  application:
    name : lsi-core
  http :
    multipart :
      location : /home/fauzi/tmp_upload
      enabled : true
      file-size-threshold : 2KB
      max-file-size : 250MB
      max-request-size : 1000MB
  profiles:
    active : prod
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://${db.host}:${db.port}/${db.name}?autoReconnect=${db.auto-reconnect}&useSSL=${db.ssl}
    username : ${db.username}
    password : ${db.password}
    hikari:
      minimumIdle: 10
      maximumPoolSize: 50
      idleTimeout: 500000
      poolName: connection-pooling-core
      maxLifetime: 2000000
      connectionTimeout: 60000
  jpa:
    show-sql: false
    properties:
      hibernate:
      dialect : org.hibernate.dialect.MySQL5Dialect
      ddl-auto : validate     # Hibernate ddl auto (create, create-drop, validate, update)

#============================================================================
# DATABASE
#============================================================================
db:
  name : lsi_core
  host : 103.77.78.248
  port : 3306
  username : trplsi
  password : trplsi0123()**!
  auto-reconnect : true
  ssl : false

#============================================================================
# ACTUATOR
#============================================================================
management:
  context-path : /actuator
  security:
    enabled: false
    roles: ROLE_ACTUATOR

#============================================================================
# FEIGN
#============================================================================
base:
  url:
    local:
      host: localhost
      actuator : /

feign:
  acl :
    api :
      base-path : http://localhost:9002/lsi-acl

#============================================================================
# LOGGER
#============================================================================
logging:
  config: classpath:logback-spring.xml
  file : ${log.file.path}
  level:
    com.tripoin.lsi.client: DEBUG
  api :
    base-path : ${log.base.path}

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/LSI/CORE/lsi-core.log
  base:
    path : http://localhost:9001/lsi-api-logger


#============================================================================
# RABBIT MQ
#============================================================================
rabbitmq:
  host : 127.0.0.1
  port : 5672
  username : guest
  password : guest
  fanout:
    exchange:
      file-upload : fanout-exchange-file-upload
  queue :
    file-upload : queue-file-upload


#============================================================================
# JWT
#============================================================================
jwt:
  secret: my-secret-app
  header: x-auth-token
# expiration in seconds
  expiration: 1800
  refresh-multiplier: 3
  cookie : JWT-AUTH
  auth:
    url : http://103.77.78.248:10002/lsi-security-oauth2/security/auth/login

#============================================================================
# OAUTH 2.0 | SSO
#============================================================================
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: app_client_id
      clientSecret: my-secret-app
      accessTokenUri: http://localhost:10002/lsi-security-oauth2/oauth/token
      userAuthorizationUri: http://localhost:10002/lsi-security-oauth2/oauth/authorize
    resource:
      userInfoUri: http://localhost:10002/lsi-security-oauth2/principal/me

sso-jwt : false


#============================================================================
# SWAGGER
#============================================================================
swagger :
  vendor :
    name : Lsi
    value : 1.0.0
  metadata :
    title : LSI - CORE
    description : Core Services for Lsi
    version : 1.0.0
    tos : This Documentation is Only Available on Development Phase
    license : Apache License Version 2.0
    license-url : https://www.apache.org/licenses/LICENSE-2.0
    contact :
      name : Achmad Fauzi
      url : https://tripoin.co.id
      email : fauzi.knightmaster.achmad@gmail.com

#============================================================================
# FLYWAY
#============================================================================
flyway :
  enabled : false

#============================================================================
# DISCOVERY CLIENT
#============================================================================
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#  instance :
#    home-page-url : http://localhost:10002/
#    status-page-url-path : http://localhost:10002/actuator/info
#    health-check-url-path : http://localhost:10002/actuator/health

#============================================================================
# INFO
#============================================================================
#info:
#  app:
#    name: Plustix Security OAuth 2.0
#    description: API for Authentication Service
#    version: 1.0.0

#============================================================================
# FILE
#============================================================================
file :
  upload :
    dir : /home/fauzi/upload


#============================================================================
#ASYNC THREAD
#============================================================================
thread:
  corepoolsize : 10
  maxpoolsize : 1000
  queuecapacity : 10000
