#============================================================================
# DATABASE
#============================================================================
db:
  name : lsi_core
  host : localhost
  port : 3306
  username : trplsi
  password : trplsi0123()**!
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /log/webservice/LSI/CORE/lsi-core.log